apiVersion: v1
kind: Secret
metadata:
  name: client1-db-secret
  namespace: odoo-client1
type: Opaque
stringData:
  db_host: "10.9.111.157"
  db_port: "5432"
  db_user: "odoo"
  db_password: "Ribentek2026+"
