apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo19-odoo-data
  namespace: odoo-odoo19
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo19-odoo-addons
  namespace: odoo-odoo19
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
