[options]
addons_path = /mnt/extra-addons/micro_saas,/mnt/extra-addons/aei_saas_manager
data_dir = /var/lib/odoo
admin_passwd = admin
# Enable proxy mode because of Nginx
proxy_mode = True
# Longpolling port
gevent_port = 8072
# Workers config (required for longpolling to activate in Odoo 17/18/19)
workers = 2
max_cron_threads = 1

; Optional: Restrict XML-RPC/NET-RPC interfaces for security [6]
; xmlrpc_interface = 127.0.0.1
; netrpc_interface = 127.0.0.1

; Optional: Hide database list from login screen
; list_db = False

; Optional: Set memory limits if needed
;limit_memory_hard = 2684354560
;limit_memory_soft = 2147483648

; Optional: Set request limits if needed
limit_request = 8192
limit_time_cpu = 600
limit_time_real = 1200

; Database filters  to land directly on the correct  db based in the  host url
#dbfilter = ^%h$


