[options]
addons_path = /mnt/extra-addons/micro_saas,/mnt/extra-addons/aei_saas_manager
data_dir = /var/lib/odoo
admin_passwd = admin
# Enable proxy mode because of Nginx
proxy_mode = True
# Longpolling port
gevent_port = 8072
# Workers config (required for longpolling to activate in Odoo 17/18/19)
workers = 2
max_cron_threads = 1
