apiVersion: v1
kind: Secret
metadata:
  name: client2-db-secret
  namespace: odoo-client2
type: Opaque
stringData:
  db_host: "patroni-db.kube-system.svc.cluster.local"
  db_port: "5432"
  db_user: "odoo"
  db_password: "Ribentek2026+"
