apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: client2-odoo-data
  namespace: odoo-client2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: client2-odoo-addons
  namespace: odoo-client2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
