apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: client2-odoo-ingress
  namespace: odoo-client2
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/custom-request-headers: "X-Forwarded-Proto: https"
spec:
  rules:
  - host: client2.aeisoftware.com
    http:
      paths:
      - path: /websocket
        pathType: Prefix
        backend:
          service:
            name: client2-odoo-svc
            port:
              number: 8072
      - path: /
        pathType: Prefix
        backend:
          service:
            name: client2-odoo-svc
            port:
              number: 8069
