apiVersion: v1
kind: Secret
metadata:
  name: odoo18-db-secret
  namespace: odoo-odoo18
type: Opaque
stringData:
  db_host: "aeisoftwaredb.postgres.database.azure.com"
  db_port: "5432"
  db_user: "odoo"
  db_password: "Ribentek2026+"
