apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo18-odoo-data
  namespace: odoo-odoo18
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo18-odoo-addons
  namespace: odoo-odoo18
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
