apiVersion: v1
kind: ConfigMap
metadata:
  name: client3-odoo-conf
  namespace: odoo-client3
data:
  odoo.conf: |
    [options]
    ; Base de Datos (Azure PostgreSQL compartido)
    db_host = 10.9.111.157
    db_port = 5432
    db_user = odoo
    db_password = Ribentek2026+
    db_name = client3
    db_filter = client3

    ; Contraseña maestra
    admin_passwd = FR2c/apWrYN/okh96NQl3lsf0EhIgLnl

    ; Rutas
    addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
    data_dir = /var/lib/odoo

    ; Rendimiento y Proxy
    workers = 2
    max_cron_threads = 1
    gevent_port = 8072
    proxy_mode = True

    ; Límites
    limit_memory_hard = 2684354560
    limit_memory_soft = 2147483648
    limit_request = 8192
    limit_time_cpu = 600
    limit_time_real = 1200
