apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo17-odoo
  namespace: odoo-odoo17
  labels:
    app: odoo
    client: odoo17
    odoo-version: "17"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odoo
      client: odoo17
  template:
    metadata:
      labels:
        app: odoo
        client: odoo17
        odoo-version: "17"
    spec:
      containers:
      - name: odoo
        image: odoo:17
        ports:
        - containerPort: 8069
          name: http
        - containerPort: 8072
          name: websocket
        env:
        - name: HOST
          valueFrom:
            secretKeyRef:
              name: odoo17-db-secret
              key: db_host
        - name: PORT
          valueFrom:
            secretKeyRef:
              name: odoo17-db-secret
              key: db_port
        - name: USER
          valueFrom:
            secretKeyRef:
              name: odoo17-db-secret
              key: db_user
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: odoo17-db-secret
              key: db_password
        volumeMounts:
        - name: odoo-data
          mountPath: /var/lib/odoo
        - name: odoo-addons
          mountPath: /mnt/extra-addons
        - name: odoo-config
          mountPath: /etc/odoo/odoo.conf
          subPath: odoo.conf
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
      volumes:
      - name: odoo-data
        persistentVolumeClaim:
          claimName: odoo17-odoo-data
      - name: odoo-addons
        persistentVolumeClaim:
          claimName: odoo17-odoo-addons
      - name: odoo-config
        configMap:
          name: odoo17-odoo-conf
