apiVersion: v1
kind: Service
metadata:
  name: odoo17-odoo-svc
  namespace: odoo-odoo17
spec:
  selector:
    app: odoo
    client: odoo17
  ports:
  - name: http
    port: 8069
    targetPort: 8069
  - name: websocket
    port: 8072
    targetPort: 8072
